services:
  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    env_file:
      - ./client/.env
    environment:
      - REACT_APP_API_URL=http://localhost:8081/api

  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
      - server_logs:/app/logs
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data:
  server_logs: